blank_issues_enabled: false
contact_links:
  - name: Ask a question
    url: https://github.com/kevinpurwito/php-constant/discussions/new?category=q-a
    about: Ask the community for help

  - name: Request a feature
    url: https://github.com/kevinpurwito/php-constant/discussions/new?category=ideas
    about: Share ideas for new features
    
  - name: Report a bug
    url: https://github.com/kevinpurwito/php-constant/issues/new
    about: Report a reproducable bug
